# Generated by Django 3.0.8 on 2020-08-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=40)),
                ('profile_pic', models.ImageField(upload_to='profile_images')),
            ],
        ),
    ]
