# Generated by Django 3.0.8 on 2020-08-02 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='feature_photos'),
            preserve_default=False,
        ),
    ]
